### ISSUE TITLE
Swift在pod install时报错

### ISSUE THREAD

**Issue by nsuxin** [netease-im/NIM_iOS_UIKit#10]
报错target has transitive dependencies that include static binaries:NIMSDK/xxxxx.a

**Comment by jimmyrogue** [comment]
@nsuxin  在podfile里添加以下语句，之后可以通过install。
```
pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end

```
**但是在build的时候仍会报错**
``` 
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by dapeng313** [comment]
I'm integrating netease-im now.
And I 've faced this error too.
I wanna finish integrating netease-im.
Any other way for it?

**Comment by dapeng313** [comment]
@jimmyrogue Had you fixed?

**Comment by yllan** [comment]
@dapeng313 作者建議手動集成（不透過 Pod）

**Comment by dapeng313** [comment]
@jimmyrogue 谢谢你.

**Comment by shenguanjiejie** [comment]
@xiangwangfeng  但是我的项目是Objective-C的呢 不是Swift. 为什么也会报这个错?

**Comment by shenguanjiejie** [comment]
找到原因了 是因为我用了use_frameworks!  现在已经好了
