### ISSUE TITLE
非网易图片无法下载展示

### ISSUE THREAD

**Issue by zolobdz** [netease-im/NIM_iOS_UIKit#106]
服务端向ios设备发送了一条图片类型的消息，且此图片不是网易图片服务器的路径（七牛）。导致无法下载和展示，需要用户自己下载处理，请问能提供具体方案吗。

**Comment by xiangwangfeng** [comment]
可以给一个无法下载的地址看一下。
可能的问题是：云信的 iOS 端会自动将所有链接转换为 https，如果外部服务器不支持 https 则无法下载。可以通过配置 NIMSDKConfig 来配置是否要做这部分的转换

**Comment by zolobdz** [comment]
是这样的，不是正常的用手机发送图片消息（选择本地图片-压缩-你们上传到网易的图片服务器）；而是用web端发的图片消息，图片链接是七牛的，不是云信的。

**Comment by xiangwangfeng** [comment]
所以提供一个无法下载的链接给我们检查下吗？

**Comment by zolobdz** [comment]
https://img.datasheetdownload.cn/a1wki87d1712010303_TAwNz.jpg 随便不是网易服务器的图片都行，只要服务端发送图片类型消息，使用非网易服务器的图片，本地都不会去下载，NIMMessage的attachmentDownloadState(NIMMessageAttachmentDownloadState)始终为NIMMessageAttachmentDownloadStateFailed

**Comment by xiangwangfeng** [comment]
参考 http://dev.netease.im/docs/interface/%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AFiOS%E7%AB%AF/NIMSDK-iOS/Classes/NIMImageObject.html#//api/name/thumbUrl

对于所有的图片/视频在聊天界面中我们都会下载缩略图，即添加相应的缩略图后缀。如果使用非云信的账号，推荐
swizzle NIMImageObject 的 thumbUrl 方法，返回 url 就可以
