### ISSUE TITLE
语音 cell 重新设置内容没有同步播放状态

### ISSUE THREAD

**Issue by cjskw** [netease-im/NIM_iOS_UIKit#11]
点击开始播放语音然后滚动列表，当重新滚动到播放语音的这个 cell 的时候显示的不是正在播放的状态，这个应该在每次为 cell 配置内容的时候查询一下当前播放的内容，现在只是在开始播放的时候设置了代理。

**Comment by hanxianlong** [comment]
啊？现在的版本已经有自动播放了啊？
我集成的那个版本，还没有这功能呢。。完全自己实现了一套跟微信一样的逻辑。。

**Comment by cjskw** [comment]
不是自动播放，是开始播放后来回滑动列表重新显示这个语音 cell 的时候没有显示正在播放的动画，但是语音是在播放的。

**Comment by hanxianlong** [comment]
哦哦，貌似我的也有这个问题。我瞅瞅该咋解决。
你真细心！

**Comment by cjskw** [comment]
我觉得这个可以在给 cell 配置数据的时候检查播放器当前播放的是不是 cell 上的那条语音来同步状态。

**Comment by chrisray108** [comment]
这个问题我们会在月底的版本上统一更新的，感谢反馈 :)
