### ISSUE TITLE
聊天键盘弹出时 退出会话界面，再次进入时inputView偏移

### ISSUE THREAD

**Issue by HelloiWorld** [netease-im/NIM_iOS_UIKit#110]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [x] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [x] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [x] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [x] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

### 问题描述
点开聊天键盘，在不关闭的情况下返回，再次进入inputView位置不对

#### 问题现象

inputView不紧贴底部

#### 是否重现

1.点击聊天框，弹出键盘
2.返回
3.再次点击进入

#### 其它备注

返回时由于界面销毁，但由于 NIMKitKeyboardInfo是单例，此时isVisiable属性仍为ture，记录的keyboardHeight仍为键盘弹出时的高度，导致下次进入界面时frame计算不正确

出错代码

    //键盘是从最底下弹起的，需要减去安全区域底部的高度
    CGFloat keyboardDelta = [NIMKitKeyboardInfo instance].keyboardHeight - safeArea.bottom;
            
    //如果键盘还没有安全区域高，容器的初始值为0；否则则为键盘和安全区域的高度差值，这样可以保证 toolBar 始终在键盘上面
    containerHeight = keyboardDelta>0 ? keyboardDelta : 0;

**Comment by HelloiWorld** [comment]
建议修改 `NIMKitKeyboardInfo.m `

    - (instancetype)init
    {
        self = [super init];
        if (self)
         {
            [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(keyboardWillChangeFrame:) name:UIKeyboardWillChangeFrameNotification object:nil];
             [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(keyboardWillShow:) name:UIKeyboardWillShowNotification object:nil];
            [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(keyboardWillHide:) name:UIKeyboardWillHideNotification object:nil];
        }
        return self;
    }

    - (void)keyboardWillHide:(NSNotification *)notification
    {
        _isVisiable = NO;
        _keyboardHeight = 0;
        [[NSNotificationCenter defaultCenter] postNotificationName:NIMKitKeyboardWillHideNotification object:nil userInfo:notification.userInfo];
    }

**Comment by chrisray108** [comment]
问题已知，会在下个版本加入此代码，感谢反馈
