### ISSUE TITLE
你好 把inputView更换为任意一个View 都会导致整个项目崩溃 而且定位不到崩溃的错误

### ISSUE THREAD

**Issue by shenguanjiejie** [netease-im/NIM_iOS_UIKit#111]
inputView和NTESSessionViewController耦合性太强了 不知道怎么分开 有没有什么建议 这个我需要换成我自己的inputView
![image](https://user-images.githubusercontent.com/9425605/34924643-9a2bff90-f9df-11e7-9c5a-393ece61dad7.png)

**Comment by chrisray108** [comment]
inputView换不了，但是现在可以换 inputView 里的 moreContainer 和 emoticonContainer，在未来的版本准备将 toolBar 的替换也开放出来
