### ISSUE TITLE
云消息记录界面显示异常

### ISSUE THREAD

**Issue by MrDML** [netease-im/NIM_iOS_UIKit#113]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [x] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [x] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [x] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [x] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

### 问题描述
在云消息记录中 下拉后界面出现异常

#### 问题现象
会话界面布局不会恢复

[描述具体问题表现]
<img width="303" alt="fbf2205e-45ed-4222-94ce-1a54c431e01b" src="https://user-images.githubusercontent.com/17716198/35078148-d38c2400-fc3b-11e7-8e8d-67f69ebb2e7d.png">

#### 是否重现
每次都可以重现

[重现此问题的步骤]

#### 其它备注

[在这里添加任何其他相关细节]

**Comment by chrisray108** [comment]
这个是官方Demo吗？ 试了下并没有复现呢，具体有做哪些改动吗？

**Comment by MrDML** [comment]
这个是官方的demo 下载后没有做任何的修改 这我边又重新下载了一次 依然有这个问题，消息记录一直下拉直到没有数据 然后快速下拉后放手 就会出现这个问题 ，查看源码后注释一行代码就不会出现这个问题了，能不能给出一个更好的解决方案谢谢
<img width="596" alt="095fccf3-7fc2-4809-9aec-d8904fbe961b" src="https://user-images.githubusercontent.com/17716198/35079627-b5c75e14-fc43-11e7-9db9-2b05e521edd1.png">

**Comment by MrDML** [comment]
我运行的是4.6.0的版本

**Comment by MrDML** [comment]
我下载了4.7.1版本也存在这个问题

**Comment by MrDML** [comment]
如果按照我那样注释会出现其他的问题，下拉之后消息会定位到最前面。
