### ISSUE TITLE
安卓端和iOS端在查看云消息记录时有部分数据对不上

### ISSUE THREAD

**Issue by MrDML** [netease-im/NIM_iOS_UIKit#114]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [x] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [x] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [x] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [x] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

### 问题描述
安卓端和iOS端在查看云消息记录时有部分数据对不上
#### 问题现象
安卓端和iOS端在查看云消息记录时有部分数据对不上
[描述具体问题表现]
没有修改过系统时间
有的消息iOS端没有 有的消息安卓短没有
#### 是否重现

[重现此问题的步骤]

#### 其它备注

[在这里添加任何其他相关细节]

**Comment by MrDML** [comment]
安卓端和iOS端在查看云消息记录时有部分数据对不上

**Comment by chrisray108** [comment]
数据问题可以到官网联系我们技术支持查询下，这里原则上只讨论组件界面相关的问题。
