### ISSUE TITLE
pod 安装下来的不是最新版本，是需要指定版本么？

### ISSUE THREAD

**Issue by wxzwork** [netease-im/NIM_iOS_UIKit#116]
您好，我通过pod 'NIMKit'的方式导入的，但是
pod update之后还是旧的版本，直接下载的话是新的版本。是pod的时候是需要指定版本么？

**Comment by chrisray108** [comment]
最新版本2.4.3  你需要pod update 之前更新下本地 pod 仓库

```
pod repo update
```
