### ISSUE TITLE
集成于NIMSessionListViewController的类是不是没法重写表格的代理呀

### ISSUE THREAD

**Issue by sjxt** [netease-im/NIM_iOS_UIKit#118]
- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView{
    return 2;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section{
    if (section == 0) {
        return 3;
    }else{
       return self.recentSessions.count;
    }
}

上面这个显示下标越界了  
在集成的类中想把表格弄成2个section  在一个section中自定义cell   大佬们有什么办法吗？

**Comment by chrisray108** [comment]
可以重写啊，你直接在上层重写代理就好了呀

**Comment by sjxt** [comment]
就是在集成的类里面重写是吧! 谢谢了
