### ISSUE TITLE
在消息列表中有没有办法固定某几个消息在表格顶部呀？

### ISSUE THREAD

**Issue by sjxt** [netease-im/NIM_iOS_UIKit#119]

**Comment by hanxianlong** [comment]
有，二次开发就行。

**Comment by sjxt** [comment]
额  好吧   有什么好的建议吗？

**Comment by chrisray108** [comment]
目前只能在上层把 UITableView 以及 NIMConversationManagerDelegate 的几个代理重写掉。接下来的版本会针对这个排序开放更便捷的接口

**Comment by sjxt** [comment]
嗯嗯  多谢了

**Comment by hanxianlong** [comment]
实现的大致思路如下：
NIMSessionListViewController中，定义一个数组，用来保存置顶的会话id,然后修改下该类中的sort方法如下


- (void)sort{
    NSMutableArray *stickArray = [[NSMutableArray alloc] init];
    [self.recentSessions sortUsingComparator:^NSComparisonResult(id obj1, id obj2) {
        
        NIMRecentSession *item1 = obj1;
        NIMRecentSession *item2 = obj2;
        if([_stickTopSessionIdArray containsObject:item1.session.sessionId] && ![stickArray containsObject:item1]){
            [stickArray insertObject:item1 atIndex:0];
            return NSOrderedSame;
        }
        if([_stickTopSessionIdArray containsObject:item2.session.sessionId] && ![stickArray containsObject:item2]){
            [stickArray insertObject:item2 atIndex:0];
            return NSOrderedSame;
        }
        
        if (item1.lastMessage.timestamp < item2.lastMessage.timestamp) {
            return NSOrderedDescending;
        }
        if (item1.lastMessage.timestamp > item2.lastMessage.timestamp) {
            return NSOrderedAscending;
        }
        return NSOrderedSame;
    }];
    
    if([stickArray count]==0){
        return;
    }
    
    [stickArray sortUsingComparator:^NSComparisonResult(id  _Nonnull obj1, id  _Nonnull obj2) {
        NIMRecentSession *item1 = obj1;
        NIMRecentSession *item2 = obj2;
        if (item1.lastMessage.timestamp < item2.lastMessage.timestamp) {
            return NSOrderedDescending;
        }
        if (item1.lastMessage.timestamp > item2.lastMessage.timestamp) {
            return NSOrderedAscending;
        }
        return NSOrderedSame;
    }];
    
    [self.recentSessions removeObjectsInArray:stickArray];
    NSMutableIndexSet *indexSet = [[NSMutableIndexSet alloc] initWithIndexesInRange:NSMakeRange(0, [stickArray count])];
    [self.recentSessions insertObjects:stickArray atIndexes:indexSet];
}

**Comment by sjxt** [comment]
好的  空了我试一试  谢谢了
