### ISSUE TITLE
怎么可以在继承的NIMSessionViewController里拿到cell？

### ISSUE THREAD

**Issue by hydyy** [netease-im/NIM_iOS_UIKit#12]
现在的需求是 我要拿到当前对话中的图片跟视频，进入类似微信那样的预览页面，这时候俩问题。

1、 我拿不到当前对话数据。 通过history拿我也不知道当前用户拉出来的有多少条。
2、我需要cell中image相对于window的位置。 这样我就必须拿到cell才可以。

这个需求蛮紧的，你们有啥建议吗？

**Comment by chrisray108** [comment]
NIMMessageCellDelegate 方法里的回调
`- (void)onLongPressCell:(NIMMessage *)message
                 inView:(UIView *)view;
`
不能满足吗？这个回调的view就是气泡的视图，根据这个视图相对Window的位置应该就能解决你的问题

**Comment by hydyy** [comment]
能把数据源开放出来就好了，现在完全拿不到数据源。
