### ISSUE TITLE
使用Cocoapod 导入库的时候出现以下问题

### ISSUE THREAD

**Issue by gj0134** [netease-im/NIM_iOS_UIKit#120]
clang: error: no such file or directory: '2'
clang: error: no such file or directory: '3'
<img width="627" alt="wx20180211-152534 2x" src="https://user-images.githubusercontent.com/6159181/36070894-d7ba2df8-0f3f-11e8-8a39-70bb70828f63.png">
<img width="426" alt="wx20180211-152518 2x" src="https://user-images.githubusercontent.com/6159181/36070895-d7ea2314-0f3f-11e8-80e7-13d665235a3d.png">

**Comment by chrisray108** [comment]
这个2 3 看起来是你自己写的other linker flag 哦
