### ISSUE TITLE
NIM_iOS_UIKit UI库中的一些适配xcode9出现的警告有没有计划给消除掉。

### ISSUE THREAD

**Issue by shaveKevin** [netease-im/NIM_iOS_UIKit#121]
NIM_iOS_UIKit 库中的一些适配xcode9出现的警告有没有计划给消除掉。

**Comment by chrisray108** [comment]
组件所依赖的第三方库出现的警告目前没有办法消除掉；组件库本身代码的警告目前应该是没有的，如果有可以上报给我们看一看。

**Comment by shaveKevin** [comment]
一种是这种问题
<img width="1254" alt="2018-02-26 11 21 03" src="https://user-images.githubusercontent.com/9313522/36652045-2e16ecba-1ae7-11e8-8081-c6cb07a513a0.png">

还有一种是通过Jenkins构建采用OCLint进行检测的时候
![2018-02-26 11 11 56](https://user-images.githubusercontent.com/9313522/36652075-522c6ca6-1ae7-11e8-9b10-5c775c4bdc47.png)
设计的类有

**Comment by chrisray108** [comment]
这个我们会在这个版本修复，谢谢反馈
