### ISSUE TITLE
修改头像后，聊天界面上下滑动有卡顿现象

### ISSUE THREAD

**Issue by tangzhentao** [netease-im/NIM_iOS_UIKit#124]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [x] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [x] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [x] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [x] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

### 问题描述
修改头像后，聊天界面消息消息较多时，上下滑动聊天界面，有卡顿，没有默认头像时流畅。
#### 问题现象

[描述具体问题表现]

#### 是否重现
能重新
[重现此问题的步骤]
找一个好友发送多条文本消息。
修改自己的头像
回到聊天界面，上下滑动
会发现不是很流畅，有卡顿现象

#### 其它备注
初步判断可能是NIMAvatarImageView中存在的问题
[在这里添加任何其他相关细节]

**Comment by tangzhentao** [comment]
修改头像后，聊天界会卡顿

**Comment by emilyzyw** [comment]
@tangzhentao 能问一下“发现不是很流畅，有卡顿现象”有什么量化指标吗，比如量化到 fps 是多少？我们提供的 demo NTESSessionViewController 里有一个 fps label可以显示。

**Comment by tangzhentao** [comment]
fps还好最多60。但是在慢慢滑动的聊天内容的时候明显能感觉到有头像的界面没有使用默认头像的聊天界面流畅。iPhone X上更明显。你对比下就能看出来了：
先使用两个未设置头像的用户，发送二三十条文字信息，慢慢滑动看下效果。
再使用两个已设置头像的用户，发送二三十条文字信息，慢慢滑动看下效果。
最好使用iPhone X对比。

**Comment by emilyzyw** [comment]
@tangzhentao 好，我这边试一试

**Comment by chrisray108** [comment]
下个版本会修复这个问题，感谢反馈
