### ISSUE TITLE
swift混编

### ISSUE THREAD

**Issue by LazyZhou** [netease-im/NIM_iOS_UIKit#126]
swift混编，直接手动添加的SDK，一句代码没改，当消息很多的时候很卡，并且tableview滑动的时候卡顿

**Comment by chrisray108** [comment]
这个消息多具体是有多大的量级？或者用 instrument 定位一下具体的耗时代码？

**Comment by LazyZhou** [comment]
5条数据都要2.64so(╯□╰)o

**Comment by chrisray108** [comment]
这个不太科学啊😨😨，能不能 instrument 定位下具体卡的代码？

**Comment by LazyZhou** [comment]
这个真不会定位，方便加我qq：541453827聊不？万分感谢！！！
[WeChatSight1.mp4.zip](https://github.com/netease-im/NIM_iOS_UIKit/files/1847299/WeChatSight1.mp4.zip)

**Comment by LazyZhou** [comment]
这个真不会定位，方便加我qq：541453827聊不？万分感谢！！！
[WeChatSight1.mp4.zip](https://github.com/netease-im/NIM_iOS_UIKit/files/1847303/WeChatSight1.mp4.zip)
