### ISSUE TITLE
气泡文本不能自适应宽度

### ISSUE THREAD

**Issue by MirrorZyb** [netease-im/NIM_iOS_UIKit#127]
NIMKit 2.4.0
在Appdelegate中通过这两行代码设置字体大小导致气泡中文本显示不全或不显示。
` [NIMKit sharedKit].config.rightBubbleSettings.textSetting.font = [UIFont systemFontOfSize:19];`
` [NIMKit sharedKit].config.leftBubbleSettings.textSetting.font = [UIFont systemFontOfSize:19];`

**Comment by xfy6238** [comment]
我这里也出现这个问题了. 原因是因为在 NIMTextContentConfig.m 文件中,
#pragma mark - Private
- (M80AttributedLabel *)label
{
    if (_label) {
        return _label;
    }
    _label = [[M80AttributedLabel alloc] initWithFrame:CGRectZero];
    _label.font = [UIFont systemFontOfSize:NIMKit_Message_Font_Size];
    return _label;
}
label的font设置成了固定值: 15;
不知道为什么:
[NIMKit sharedKit].config.leftBubbleSettings.textSetting.font = [UIFont systemFontOfSize:19];
这种设置并不起作用, 具体原因没有查询.

**Comment by chrisray108** [comment]
这个修正在下个版本会上线
