### ISSUE TITLE
用cocoapods 老是报错

### ISSUE THREAD

**Issue by wangyu204** [netease-im/NIM_iOS_UIKit#13]
错误：[!] Error installing NIMKit
[!] /usr/local/bin/git clone https://github.com/netease-im/NIM_iOS_UIKit.git /var/folders/g3/r8328tc109769fx71cnm85lm0000gn/T/d20161217-61847-121cm75 --template= --single-branch --depth 1 --branch 1.0.5

Cloning into '/var/folders/g3/r8328tc109769fx71cnm85lm0000gn/T/d20161217-61847-121cm75'...
error: RPC failed; curl 56 SSLRead() return error -9806
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

已经做过如下处理
1.换网络尝试还是不行（只装一个xocde也不行）
2.给git 增加缓存数量
git config --global http.postBuffer 524288000
3.stackOverflow上用如下命令操作后在  pod install （pod install --no-repo-update）
$ brew remove git
$ brew remove curl
$ brew install openssl
$ brew install --with-openssl curl
$ brew install --with-brewed-curl --with-brewed-openssl git
4.第四种方法也不行
http://blog.csdn.net/fatalibud/article/details/48649963
$ brew tap homebrew/dupes
$ brew tap homebrew/versions
$ brew tap homebrew/php
$ brew install --with-openssl curl
$ brew install --with-fpm --with-homebrew-curl --with-homebrew-openssl --without-snmp php55
$ brew install php55-mcrypt
$ php -i | grep "SSL Version"

我的Podfile是这样的：【SDWebImage这些都是可以安装的】
platform :ios, '8.0'
target "HuNIMDemo" do
pod 'NIMKit/Lite'
end

**Comment by chrisray108** [comment]
试试挂个 Shadowsocks, 终端输入以下命令
`
git config --global http.proxy 'socks5://127.0.0.1:1080' 

git config --global https.proxy 'socks5://127.0.0.1:1080'

`
shadowsocks 的本地端口默认是1080，如果有改动的话替换成你改动的端口
pod setup 一下再试试。
