### ISSUE TITLE
语音消息类型, 右侧使用的也是左侧类型的图标. 官方demo即是如此, 请问该怎么修改?

### ISSUE THREAD

**Issue by xfy6238** [netease-im/NIM_iOS_UIKit#130]
语音消息类型, 右侧使用的也是左侧类型的图标. 官方demo即是如此, 请问该怎么修改?

**Comment by chrisray108** [comment]
NIMKitConfig单例中有个 leftBubbleSettings/ rightBubbleSettings 属性，里头有各种消息的布局设置，包括消息背景设置

**Comment by xfy6238** [comment]
是我描述的不太清. 那个图标是语音消息的播放图标(小喇叭), NIMSessionAudioContentView.m文件中,只设置了左侧的小喇叭,我没找到设置相关接口. 我解决的办法是在.m文件中,直接判断是左侧还是右侧,然后进行设置(小喇叭)

**Comment by chrisray108** [comment]
哦哦，这个接下来的版本会考虑加上
