### ISSUE TITLE
关于IM中过滤自定义消息的问题

### ISSUE THREAD

**Issue by shaveKevin** [netease-im/NIM_iOS_UIKit#131]
关于IM中过滤自定义消息：只是在IM聊天记录里不展示，咱们这边有没有好的建议。我们目前的做法是 在NIMSessionMsgDatasource 中resetMessages:(void(^)(NSError *error)) handler 过滤掉对应的消息。这样做分页就不那么准确了。有没有好的解决方案。

**Comment by chrisray108** [comment]
NIMSessionConfig 中有个消息提供数据源 messageDataProvider， 重写消息数据源，每次通过SDK搜索消息接口

```
// NIMConversationManagerProtocol
- (void)searchMessages:(NIMSession *)session
                option:(NIMMessageSearchOption *)option
                result:(nullable NIMSearchMessageBlock)result;
```

控制消息类型和分页大小，然后将结果作为消息源显示
