### ISSUE TITLE
输入框可以只保留按住说话按钮么

### ISSUE THREAD

**Issue by AlanZane** [netease-im/NIM_iOS_UIKit#133]
配置NIMSessionConfig的- (NSArray<NSNumber *> *)inputBarItemTypes，只保留NIMInputBarItemTypeVoice的话只会是保留录音按钮，要点击一次录音按钮后才会出现按住说话，我需要输入框只保留按住说话的按钮。

**Comment by chrisray108** [comment]
这个接口主要是改变排版顺序用的，你可以试试多调用一个 refreshStatus: 接口

```objc

// SessionViewController 里

...
[self.sessionInputView refreshStatus:NIMInputStatusAudio];
...

```

**Comment by AlanZane** [comment]
这个我有用，在viewDidLoad和viewWillAppear中使用，内部在之后还会调用这个接口修改成别的status，导致无法生效。
目前我是在viewDidAppear中调用，可以实现只保留按住说话的按钮，但是在按住一次后会变成如图这样
![img_1475](https://user-images.githubusercontent.com/17693754/39982543-4b526d68-5787-11e8-9688-c4de20700638.jpg)

**Comment by chrisray108** [comment]
应该是怎么样的？

**Comment by AlanZane** [comment]
![img_1476](https://user-images.githubusercontent.com/17693754/39983271-ab0c7224-5789-11e8-82e4-5c395869248b.PNG)

正常是这样的，按过一次后会在上面多出一条白色的

**Comment by chrisray108** [comment]
看看是不是viewDidAppear重复调用了？

**Comment by AlanZane** [comment]
controller是继承自NIMSessionViewController的，只在viewDidAppear中调用过一次refreshStatus，打断点也只走了一次viewDidAppear。
我看了下层级，是按了一次后，聊天信息的tableView的高度变小了一点点。
