### ISSUE TITLE
聊天界面是否支持中英文互相翻译?

### ISSUE THREAD

**Issue by xfy6238** [netease-im/NIM_iOS_UIKit#134]
如标题, 文字消息是否支持翻译?

**Comment by emilyzyw** [comment]
你说的翻译是指适配 i18n 的意思吧，这个放在下个版本实现

**Comment by xfy6238** [comment]
就是中文翻译成英文,英文翻译成中文. 下个版本预计什么时候实现呢?

**Comment by emilyzyw** [comment]
嗯  就是确认一下，因为你提到微信翻译还有一种理解是每一条消息长按会有个翻译，所以又问了一下确认一下。下个版本预计 6月26号前后吧

**Comment by xfy6238** [comment]
嗯 好的  谢谢
