### ISSUE TITLE
能否把依赖的SDWebImage版本，去依赖本地化呢

### ISSUE THREAD

**Issue by maltsugar** [netease-im/NIM_iOS_UIKit#136]
主要是这个库依赖的SD版本低，和别的库冲突。能否把SDWeb的库全部加上前缀，然后去掉pod依赖呢

**Comment by emilyzyw** [comment]
首先升级到新的 NIMKit，然后参考 NIMAvatarImageView 类的实现

**Comment by maltsugar** [comment]
只是用pod管理 改源码很不方便，下次升级时 直接又得重改一遍，我现在都是尽量少改源码，必须改的用 method_exchangeImplementations

**Comment by maltsugar** [comment]
我觉得做一个用户量比较大的库，还是将用到的第三方库，加前缀比较好。并且你依赖的还不是最新的版本，如果都依赖最新版本还无所谓

**Comment by emilyzyw** [comment]
我们的 SD 版本现在是 4.2.3 ，想问一下你用的什么版本呢，每次升级都有 SD 的兼容问题？

**Comment by maltsugar** [comment]
不是的，比方说我自己改了NIMAvatarImageView类里源码，升级时不就pod被覆盖了。
我用其他的库 SD版本依赖的是 4.3.3，基本就是最新的版本，这样pod无法安装。
你们可否考虑不指定sd版本，当然这样也可能有问题，最好就是常用库本地化

**Comment by maltsugar** [comment]
O__O "… SD比较流行，我集成库，3个都有依赖。那几个库 不指定SD版本还好，最近又要集成一个指定版本的，就不行了。只能先不用了

**Comment by maltsugar** [comment]
只是个建议😬

**Comment by kennenfromchina** [comment]
NIMKit的SDWebImage指定版本和其他第三方也指定的版本不一致，导致冲突，怎么解决的？

**Comment by maltsugar** [comment]
没法解决 只能舍弃一个

**Comment by ElfSundae** [comment]
如果项目中用到的 SDWebImage 是 5.0 以上的版本，可以安装 NIMKit 的 Free 版：
Podfile 中把原来的 `pod 'NIMKit'` 改成 `pod 'NIMKit/Lite_Free'` 或者  `pod 'NIMKit/Full_Free'`
