### ISSUE TITLE
聊天时, 点击语音进行播放, 点击home键回到桌面, 语音停止播放; 回到APP, 语音接着播放; 该怎么设置,实现回到APP, 语音是未播放状态;只能重新点击,开始正常播放; 

### ISSUE THREAD

**Issue by xfy6238** [netease-im/NIM_iOS_UIKit#137]
聊天时, 点击语音进行播放, 点击home键回到桌面, 语音停止播放; 回到APP, 语音接着播放; 该怎么设置,实现回到APP, 语音是未播放状态;只能重新点击,开始正常播放; 

想要的功能效果和微信一样; 播放到一般,回到桌面,再 进来就不需要再播放了

**Comment by emilyzyw** [comment]
正常情况下 app 退到后台会有一段时间运行，因此音频会持续播放，若音频较长是可能被中断，但我们的 Demo 开了针对音视频的后台模式，所以会一直播放；微信可能是出于产品体验的角度，退到后台就暂停，所以做了音频停止播放设置。
