### ISSUE TITLE
5.5尺寸 输入框bug

### ISSUE THREAD

**Issue by xfy6238** [netease-im/NIM_iOS_UIKit#139]
在5.5尺寸的设备上,在输入框输入大量表情, 在textview的高度大道最大值时,继续输入, 换行出现问题.仍能够输入文字呵呵表情,但不会自动换行,仍然显示之前的文字. 需要手动滑到最底部,接着输入,换行正常,显示正常;  目前只在5.5寸上发现这个问题. 4.7寸正常

**Comment by emilyzyw** [comment]
感谢反馈，我们这边修复一下
