### ISSUE TITLE
我们要把图片cell 和 视频cell 做的跟微信类似

### ISSUE THREAD

**Issue by hydyy** [netease-im/NIM_iOS_UIKit#14]
现在kit中的 图片 视频 cell 都会在下面铺image，看起来还是有那么点不和谐的，不知道怎么做比较合适？

**Comment by chrisray108** [comment]
没明白什么意思，你指的铺的image是气泡的image吗？  这个是可以定制的，NIMKitGlobalSetting.plist 以及 NIMKitBubbleSetting.plist 中的 Bubble 字段可以分别定制气泡的全局和特殊类型的图片，如果不要图的话置空就好了。

**Comment by hydyy** [comment]
变成空的话，就没有箭头了， 就一个图片在那里跟贴纸样式一样的了。  微信的图片或者视频，图片也有mask的， 会漏出来指向头像的箭头

**Comment by HuaYunZhangKe** [comment]
虽然服务挺稳定，但是要和微信做的一样是不显得没创建

**Comment by HuaYunZhangKe** [comment]
虽然服务很稳定，但做的和微信一样是不是显得有点追求有点低呢
