### ISSUE TITLE
自定义cell，如何让它居中？类似通知

### ISSUE THREAD

**Issue by hydyy** [netease-im/NIM_iOS_UIKit#15]
如题， 真的是跟了很久代码， 但是看的很晕。 只看到一个showleft。

**Comment by chrisray108** [comment]
可以参考下 Demo 中对 Tip 类型消息的实现，这个是排版是实现在组件之上的。主要还是通过指定消息的内容大小以及算好内容对 Cell 的边距，来实现居中的。

**Comment by hydyy** [comment]
好的 我看看  其实就是计算padding的哇 ？
