### ISSUE TITLE
消息删除时不管在列表的任何位置都会回到底部。

### ISSUE THREAD

**Issue by NameWZZ** [netease-im/NIM_iOS_UIKit#154]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [x] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [x] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [x] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [x] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

#### 问题现象

[描述具体问题表现]

#### 是否重现

[重现此问题的步骤]

#### 其它备注

[在这里添加任何其他相关细节]

**Comment by NameWZZ** [comment]
要删除的cell
![image](https://user-images.githubusercontent.com/7778114/43456893-a9c57842-94f7-11e8-8405-67df07318333.png)

实际执行remove：
![image](https://user-images.githubusercontent.com/7778114/43456946-dc124708-94f7-11e8-8096-cf227ae34de3.png)

![image](https://user-images.githubusercontent.com/7778114/43456970-f0880362-94f7-11e8-93c5-f8d99f5df76e.png)

最终结果执行remove是一个时间戳的cell。这段判断的代码是我自行添加的，个人认为所以才会导致删除cell时table展示位置错误。你们采用了只要删除就自动滑到底部，不知道是否是因为删除cell时table会错位？

**Comment by NameWZZ** [comment]
通过判断tableView的offset来固定table的位置来解决。else只是一个定时器去检查cell是否已成功删除的容错。使用Category来替换NIMSessionLayoutImpl的remove方法
![image](https://user-images.githubusercontent.com/7778114/43457830-a60780ee-94fa-11e8-98ae-3110f2839bbf.png)

**Comment by emilyzyw** [comment]
谢谢反馈 下个版本会修复
