### ISSUE TITLE
会话中的图片可否放大预览？拍摄按钮能否禁止拍摄视频？

### ISSUE THREAD

**Issue by lwy121810** [netease-im/NIM_iOS_UIKit#158]
1. 会话中的图片有点击方法查看大图的方法吗？ 还是需要自己来实现？
2. inputView的更多功能面板中的拍摄按钮，能否只让拍摄照片，不拍摄视频

**Comment by emilyzyw** [comment]
1. 对 自己实现
2. 自己可以改造一下，这边暂时不打算改动
