### ISSUE TITLE
对不支持消息的兼容

### ISSUE THREAD

**Issue by cjskw** [netease-im/NIM_iOS_UIKit#18]
现在的处理是这里设置了一个断言供 debug， Release 版不支持的消息会返回空的 cell 导致崩溃。我觉得比较好的一个处理是对不支持的消息专门设置一个提示的 cell 来保证旧版本的兼容性。

**Comment by xiangwangfeng** [comment]
NIMKit里面对不支持的消息是返回一个默unsupport cell的，可以查看下代码。
