### ISSUE TITLE
消息重发问题

### ISSUE THREAD

**Issue by huangxianyu** [netease-im/NIM_iOS_UIKit#216]
![WX20190731-175644](https://user-images.githubusercontent.com/20720740/62202831-9c5bdb80-b3bc-11e9-876d-e0cbb1a0a48a.png)
消息发送失败后, 点击重发, 重发成功了, 下次再进入本聊天界面, 重发的消息会在最下面...

**Comment by huangxianyu** [comment]
重发消息后, 怎么直接把重发的消息插在最下面?

**Comment by zhanggenning** [comment]
是因为重发的时候会把消息的时间戳更新掉，session每次进入的时候都是按照时间戳排序来进行显示的，这个问题你可以在消息发送成功的时候使用uiDeleteMessage:删除本条消息，再uiAddMessages：将该消息插入到最后面就可以了
