### ISSUE TITLE
CocoaPods集成时遇到的问题

### ISSUE THREAD

**Issue by friendsheeps** [netease-im/NIM_iOS_UIKit#222]
### 问题描述
用CocoaPods集成时，首先pod repo update之后本地仓库和用pod search NIMKit 都可以看到2.12.1，但pod 'NIMKit' 导入的是1.8.0版，直接pod 'NIMKit', '~> 2.12.1' 则会出现之前pod进去的第三方库报错，比如SDWebImage和TZImagePickerController，例如TZ这个库，之前导入的版本是3.2.0，但是NIMKit 2.12.1 版依赖的是3.0.7
<img width="412" alt="屏幕快照 2019-08-15 上午10 47 08" src="https://user-images.githubusercontent.com/13128046/63070446-cd581680-bf4d-11e9-870a-76e21818f1b7.png">

<img width="310" alt="屏幕快照 2019-08-15 上午10 55 02" src="https://user-images.githubusercontent.com/13128046/63070440-c92bf900-bf4d-11e9-9fe7-0a896b0e8235.png">

<img width="623" alt="屏幕快照 2019-08-15 上午11 01 37" src="https://user-images.githubusercontent.com/13128046/63070432-c204eb00-bf4d-11e9-9977-36c3c1f5d75a.png">

**Comment by ElfSundae** [comment]
是不是你 Podfile 里其他的库跟 NIMKit 的依赖有冲突，可以试试[我的分支](https://github.com/ElfSundae/NIM_iOS_UIKit)看能安装不：
```ruby
pod 'NIMKit', :source => 'https://github.com/ElfSundae/CocoaPods-Specs.git'
```
