### ISSUE TITLE
“按住说话”按钮高度问题

### ISSUE THREAD

**Issue by raykle** [netease-im/NIM_iOS_UIKit#23]
步骤：
1. 任意聊天界面，输入框文字内容输入超过一行。
2. 点击“语音”按钮，切换到语音录入界面。

结果：“按住说话”按钮高度不对。

`NIMInputToolBar` 中在方法 `- (void)adjustTextAndRecordView` 中始终设置了 `self.recordButton.frame    = self.inputTextBkgImage.frame;`， 导致了按钮高度一直等于输入框背景高度。

**Comment by chrisray108** [comment]
感谢，这个问题已经在下个版本修复，下版本会话本月中下旬上线。
