### ISSUE TITLE
cocoapods安装问题

### ISSUE THREAD

**Issue by bingolib** [netease-im/NIM_iOS_UIKit#234]
服了！ 搞了半天NIMKit一直是1.8.0  最后发现要指定SDWebImage为5.0.6版本才行！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by ElfSundae** [comment]
啥意思

**Comment by zhanggenning** [comment]
我们现在是这样的，如果使用NIMKit，NIMKit/Full，NIMKit/Lite那么就是有第三方依赖库的版本限制的，对于指定的第三方库因为我们走过质量保证流程，因此可以保证NIMKit的稳定性。如果不希望有第三方版本限制，可以使用NIMKit/Full_Free或NIMKit/Lite_Free，这个去除了第三方依赖库的版本限制，但是我们不保证NIMKit在您使用的第三方库上的稳定性以及编译是否可以通过。

**Comment by bingolib** [comment]
> 我们现在是这样的，如果使用NIMKit，NIMKit / Full，NIMKit / Lite那么就是有第三方依赖库的版本限制的，对于指定的第三方库，因为我们走过质量保证流程，因此可以保证NIMKit的稳定性。如果不希望有第三方版本限制，可以使用NIMKit / Full_Free或NIMKit / Lite_Free，这个删除了第三方依赖库的版本限制，但是我们不保证NIMKit在您使用的第三方库上的稳定性以及编译是否可以通过。

并不介意指定版本，只是你文档中没有说明，浪费精力去找问题所在。
