### ISSUE TITLE
部分表情资源未提交

### ISSUE THREAD

**Issue by fengong** [netease-im/NIM_iOS_UIKit#243]
NIMKit/Resources/NIMKitEmoticon.bundle/Emoji 下的表情只有部分

**Comment by ElfSundae** [comment]
你看下 plist 文件，部分表情图片用 iOS 系统自带的 Emoji 字符代替了。

**Comment by fengong** [comment]
![IMG_5594](https://user-images.githubusercontent.com/7297272/68270012-d5c87500-0096-11ea-8e44-aff7db8890e3.PNG)
UIImage 的  nim_emoticonInKit 方法不能读取到 Bundle 里面的图片，返回 nil

**Comment by ElfSundae** [comment]
应该是这个问题 https://github.com/netease-im/NIM_iOS_UIKit/pull/227
可以试试：
```ruby
pod 'NIMKit', :source => 'https://github.com/ElfSundae/CocoaPods-Specs.git'
```

**Comment by tsaievan** [comment]
没解决问题啊
