### ISSUE TITLE
遇到极个别的消息串群问题，不好定位，是服务的问题吗？

### ISSUE THREAD

**Issue by lgb1234a** [netease-im/NIM_iOS_UIKit#246]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [ ] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [ ] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [ ] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [ ] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

#### 问题现象

[描述具体问题表现]

#### 是否重现

[重现此问题的步骤]

#### 其它备注

SDK Version: 6.9.1

**Comment by lgb1234a** [comment]
SDK Version: 6.9.1
当前的解决方案是：当navigation堆栈中存在同session的view controller，就销毁栈底的vc，保留top vc，几个月来未收到串群反馈。

**Comment by lgb1234a** [comment]
但是这种解决办法连办法都称不上，所以希望有官方提供一下其他的定位思路。

Kit框架采用的是demo里面的，然后魔改了几个版本，问题又极难复现。

**Comment by zhanggenning** [comment]
收到消息的时候，将message里的session跟当前vc的session对比一下

**Comment by lgb1234a** [comment]
> 收到消息的时候，将message里的session跟当前vc的session对比一下

```//接收消息
- (void)onRecvMessages:(NSArray *)messages
{
    if ([self shouldAddListenerForNewMsg])
    {
        NIMMessage *message = messages.firstObject;
        NIMSession *session = message.session;
        if (![session isEqual:self.session] || !messages.count)
        {
            return;
        }
        
        [self uiAddMessages:messages];
        [self.interactor markRead];
    }
}

是按照demo里的处理方式处理的。

**Comment by zhanggenning** [comment]
出现串群的情况，主要是因为你的VC管理问题，在addDelegate的时候，错把其他session的消息添进了当前的vc，我这边的建议就是，查一下你代码里的adddelegate逻辑从根本上解决问题，也可以像我刚才说的那样，确定是当前session的消息再显示，不过这样可能会丢失一些消息。

**Comment by lgb1234a** [comment]
> 出现串群的情况，主要是因为你的VC管理问题，在addDelegate的时候，错把其他session的消息添进了当前的vc，我这边的建议就是，查一下你代码里的adddelegate逻辑从根本上解决问题，也可以像我刚才说的那样，确定是当前session的消息再显示，不过这样可能会丢失一些消息。

谢谢大佬，排查过一遍，发现确实在每次添加音频代理的时候，录音发送结束后没有移除，当push一个新的vc，用户再次录音的时候，前一个vc的录音代理方法也会调用。

太感谢了！！！
