### ISSUE TITLE
NIMAvatarImageView初始化造成崩溃

### ISSUE THREAD

**Issue by haijunli68** [netease-im/NIM_iOS_UIKit#259]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [x] 我已经阅读了组件文档: 

     [《项目结构介绍》](./Documents/nim_arch.md)

     [《界面排版自定义》](./Documents/nim_custom_ui.md)

     [《新消息类型集成》](./Documents/nim_custom_message.md)

     [《用户信息自定义》](./Documents/nim_userinfo.md)

     [《机器人消息排版指南》](./Documents/nim_robot.md)

- [x] 我已经阅读了[常见问题](http://dev.netease.im/docs/product/%E9%80%9A%E7%94%A8/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98?#iOS%E7%89%88SDK), 但是找不到相关解决方案。

- [x] 我已经阅读了[SDK 文档](http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/%E6%A6%82%E8%A6%81%E4%BB%8B%E7%BB%8D), 但是找不到相关解决方案。
     
- [x] 我已经搜索了[当前问题](https://github.com/netease-im/NIM_iOS_UIKit/issues?utf8=✓&q=is%3Aissue), 但是找不到相关解决方案。

### 问题描述
NIMAvatarImageView初始化造成死循环
#### 问题现象
崩溃
[描述具体问题表现]
自定义消息列表，引用了NIMAvatarImageView类创建头像，app启动，切换到消息列表崩溃
#### 是否重现
是
[重现此问题的步骤]
自定义消息列表，引用NIMAvatarImageView类创建头像
#### 其它备注
![image](https://user-images.githubusercontent.com/13010224/76823372-fe375b80-684e-11ea-9424-39be06e69b9c.png)

[在这里添加任何其他相关细节]

**Comment by ElfSundae** [comment]
挂在哪行代码了？

**Comment by haijunli68** [comment]
@ElfSundae [NIMKit sharedKit]的dispatch_once

**Comment by haijunli68** [comment]
手动集成NIMKIt会出现此问题，使用cocoapods集成没问题

**Comment by ElfSundae** [comment]
资源文件没添加全吧，把最新代码 Resources 目录下的三个 bundle 拖到项目里。

**Comment by haijunli68** [comment]
新版SDK已修复，对比了下老版，就是这里的问题
![Uploading image.png…]()
