### ISSUE TITLE
对话页面的图片和视频没有缩略图

### ISSUE THREAD

**Issue by cirelir** [netease-im/NIM_iOS_UIKit#26]
通过漫游获取的聊天记录信息，在对话页面显示是黑色的，没有缩略图怎么解决？

**Comment by xiangwangfeng** [comment]
这个地方再拿到 messages 后可以主动调用一波 fetchAttachments 的接口去获取。

**Comment by cirelir** [comment]
没有这个接口啊，能不能说一下在哪个类里面？谢谢

**Comment by xiangwangfeng** [comment]
http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90?#接收消息
