### ISSUE TITLE
pod 'NIMKit/Full'出现NIMKIT文件夹为空的情况

### ISSUE THREAD

**Issue by Shandawei** [netease-im/NIM_iOS_UIKit#27]
pod install打印如下
Installing NIMKit (1.3.0)
Installing NIMSDK (3.6.0)
但是发现Pods>NIMKit内全部为空

**Comment by Shandawei** [comment]
release1.3进行pod亦会出现如上问题

**Comment by chrisray108** [comment]
已修复。
