### ISSUE TITLE
pod install后出问题

### ISSUE THREAD

**Issue by hengchengfei** [netease-im/NIM_iOS_UIKit#29]
pod install后，报如下错误。

![1](https://cloud.githubusercontent.com/assets/3182964/25600737/de2e197c-2f18-11e7-86f7-1ceecdba1285.jpeg)

**Comment by chrisray108** [comment]
确认下 pod install 日志，是不是 `NIMSDK` pod 失败了？

**Comment by hengchengfei** [comment]
pod install,是正常的。

XCode:
Version 8.3 (8E162)

Cocoapods:
1.2.1

pod 'NIMKit'

**Comment by hengchengfei** [comment]
NIMKit包里引用NIMSDK，找不到

**Comment by hengchengfei** [comment]
新建一个空白项目，什么都不操作，pod install成功后，编译还是有问题

**Comment by hengchengfei** [comment]
原因找到了，是因为在Podfile中，是以use_frameworks形式编译。
而CocoaPods是不允许静态库作为依赖项的。
所以，虽然pod的是NIMKit，但是其依赖的NIMSDK是静态的。
解决办法，删除pods中的NIMSDK，手动拖入即可。
[https://github.com/segment-integrations/analytics-ios-integration-optimizely/issues/8](url)
