### ISSUE TITLE
Too Many Errors

### ISSUE THREAD

**Issue by BMR731** [netease-im/NIM_iOS_UIKit#3]
In NIMKitUtil.m file, so many errors occured, i see the reason is serval Enums in switch struct, there is not exist the Type,but you case it,so the compile failed,

**Comment by WangBoX** [comment]
我接入云信的界面库后，聊天界面的语音按钮响应事件的问题。问题重现描述：点击 ［按住说话］，后，手势向上滑动，不松开，再次返回原位置，如此反复两次。然后就出现如图界面，无法控制录制的语音长度，录音button的响应事件失效。想知道是什么原因导致的，随来此求助，谢谢。

**Comment by chrisray108** [comment]
NIMKit is based on static lib NIMSDK,  Do you import "NIMSDK.h"?
