### ISSUE TITLE
#import <NIMKit/NIMKit.h>出错

### ISSUE THREAD

**Issue by hengchengfei** [netease-im/NIM_iOS_UIKit#31]
通过pod install安装。
#import <NIMSDK/NIMSDK.h>没有问题。

<img width="1382" alt="screen shot 2017-05-02 at 5 54 31 pm" src="https://cloud.githubusercontent.com/assets/3182964/25613335/6eb27b68-2f60-11e7-93d4-779d5a946360.png">

**Comment by xiangwangfeng** [comment]
和 https://github.com/netease-im/NIM_iOS_UIKit/issues/29 相同的问题。

**Comment by hengchengfei** [comment]
#29 ，pod install后，编译能正常通过。
但是在app中，import时，还是有问题啊。

**Comment by xiangwangfeng** [comment]
推荐使用手动导入 NIMKit 的方式在 swift 中使用 NIMKit
https://github.com/netease-im/NIM_iOS_UIKit/blob/master/Documents/nim_mi.md
通过 pod install 包括 NIMSDK ， 各个第三方库，然后在主工程中以源码的形式导入 NIMKit

**Comment by hengchengfei** [comment]
OK，我试试。

**Comment by xiangwangfeng** [comment]
目前的依赖的第三方库还没支持 framework 和 静态库同时使用的流程
所以推荐先改下 NIMKit 中的代码，通过 __has_include 来兼容

例：
#if __has_include(<AFNetworking/AFNetworking.h>)
#import <AFNetworking/AFNetworking.h>
#else
#import "AFNetworking.h"
#endif

**Comment by hengchengfei** [comment]
@xiangwangfeng 谢谢你啦，已经解决了，更新了上述项目。

Swift项目，总结一下：
1、pod NIMSDK，而不是pod NIMKit
2、NIMKit手动拖入到Project中（包含Resources）
3、因为NIMKit是手动添加，所以需要在pod中添加其第三方依赖
4、因为NIMSDK以Framework形式添加，NIMKit是非Framework，所以在bridging中添加
      #import <NIMSDK/NIMSDK.h>
      #import "NIMKit.h"

[https://github.com/hengchengfei/NIMTest.git](url)
