### ISSUE TITLE
You should call login api before calling any im related api

### ISSUE THREAD

**Issue by hjh-debug** [netease-im/NIM_iOS_UIKit#312]
[[[NIMSDK sharedSDK] loginManager] login:@"login"
                                       token:@"token"
                                  completion:^(NSError *error) { } ];

login、token均设置完成

**Comment by 190709670** [comment]
老哥,最后怎么解决的?

**Comment by sclcoder** [comment]
这个问题就是，退出IM后，又调用了NIMSDK 相关的服务了。 应该是业务代码导致的，可以通过云信内部日志看一下，具体是调用了哪些业务触发了这个提示。我也遇到了这个问题，通过排查发现是自己的业务代码有内存泄漏。
