### ISSUE TITLE
InputToolBar 中的控件位置偏移错误。

### ISSUE THREAD

**Issue by raykle** [netease-im/NIM_iOS_UIKit#33]
导航栏使用 Opaque Navigation Bar 时，点击拍摄弹出拍摄界面，点击取消或者拍摄照片并发送，拍摄界面 dismiss 之后，toolBar 上的控件位置都偏移了。

如图：

![img_1200](https://cloud.githubusercontent.com/assets/3097366/25700037/5efdf30c-30f8-11e7-9ee7-dbc915c5f601.PNG)

**Comment by robertzhang** [comment]
+1 这个问题挺奇葩的。

**Comment by snailzzj** [comment]
+1

**Comment by chrisray108** [comment]
这个是由于 inputView 的 auto resize 造成的，最新版本已经修复了
