### ISSUE TITLE
导入pod的问题

### ISSUE THREAD

**Issue by TonyXuChen** [netease-im/NIM_iOS_UIKit#36]
使用pod 'NIMKit/Full'导入完整的nimkit的时候，最新的版本是1.3.0，但是导入完成之后nimsdk的文件夹有内容，但是nimkit的文件夹是空的

**Comment by chrisray108** [comment]
已修复。

**Comment by MoYingD** [comment]
Cocoapods 集成SDK时遇到了libssl.a和libscrypto.a静态库冲突的问题, 怎么使用 post_install 方法进行冲突静态库的去除？能提代码吗？
