### ISSUE TITLE
打开 use_frameworks! ，引入 pod 'NIMKit/Full' 会报错

### ISSUE THREAD

**Issue by robertzhang** [netease-im/NIM_iOS_UIKit#38]
如题，使用swift开发。报错内容为：
The 'Pods-swift' target has transitive dependencies that include static binaries
尝试注释 use_frameworks! 后 pod install 正常，但无法再引入其他的库。会提示缺少 use_frameworks! 
请问有解决办法么？

**Comment by xiangwangfeng** [comment]
swift 目前可以使用 pod 加载 NIMSDK 但是推荐使用集成源码的方式来集成 NIMKit 
原因是 cocoapods 并不支持现在这种模式的加载
