### ISSUE TITLE
swift开发，如何修改 NIMSessionViewController titleLabel的颜色和大小

### ISSUE THREAD

**Issue by robertzhang** [netease-im/NIM_iOS_UIKit#39]
如题，我在项目中使用 swift 进行开发，想要修改sessionTitle的大小和颜色。但 swift 调用 OC 的时候，只能使用 NIMSessionViewController.h 文件中暴露出来的方法和属性，然而 titleLabel 并没有暴露出来。请问我现在有其他办法可以修改 title 的属性么？

**Comment by chrisray108** [comment]
下个版本会把主标题和子标题的 Label 暴露出来，在 父类 ViewDidLoad 之后配置字体大小颜色即可。
