### ISSUE TITLE
聊天用户的默认头像的问题

### ISSUE THREAD

**Issue by zsading** [netease-im/NIM_iOS_UIKit#41]
在NIMSessionViewController中，似乎没有提供接口来设置用户的本地默认头像。
如何来设置聊天页面中用户的本地默认头像呢？

**Comment by xiangwangfeng** [comment]
有两种做法
1.直接将默认用户默认头像命名为 user_avatar，详将 NIMKitDataProviderImpl
2.实现NIMKitDataProvider协议，然后通过 NIMKit 进行注入

**Comment by zsading** [comment]
user_avatar -> avatar_user. it works for me.
