### ISSUE TITLE
再提一个无伤大雅的Bug

### ISSUE THREAD

**Issue by cirelir** [netease-im/NIM_iOS_UIKit#42]
在iOS10上输入拼音点删除时，自动把剩余的拼音当成英文填充到输入框了，而并不是想iOS8一样，删除一个字母后仍然是拼音联想状态，还望告知一下兼容办法，谢谢

**Comment by cirelir** [comment]
告诉你一声，这个问题我解决了

**Comment by RedeemD** [comment]
麻烦问一下解决办法....

**Comment by cirelir** [comment]
我怎么告诉你啊？

**Comment by RedeemD** [comment]
可以直接在这边回复? 简单说一下思路....
谢啦

**Comment by cirelir** [comment]
- (BOOL)shouldChangeTextInRange:(NSRange)range replacementText:(NSString *)text
这个回调在iOS8 和iOS10 （iOS9没有测，没有机子）下返回的range是不一样的，我就是根据这个改的

**Comment by RedeemD** [comment]
问题是找到了.
解决方案是通过判断当前键盘的输入模式判断么, 
那怎么判断当前输入的选中范围呢....

**Comment by cirelir** [comment]
不用判断选中范围，你只要区分那个range，然后给上面那个回调return yes就可以了

**Comment by smallSmallWhite** [comment]
区分那个范围是什么意思？？？有没有具体的实现代码？？？

**Comment by cirelir** [comment]
![592822f6-efc2-4d5a-a582-b2a5dab177d0](https://user-images.githubusercontent.com/15341952/27857357-f037b408-61a3-11e7-9510-473f91acd3bc.png)
![c1f1bf80-28df-4cf7-b1d1-7f32143a6070](https://user-images.githubusercontent.com/15341952/27857362-f16537c4-61a3-11e7-998e-b7eeeed1ff97.png)
把这两个函数改一下就好了

**Comment by cirelir** [comment]
这个解决方式有个bug，这里需要在删除的地方判断一下是否是系统键盘里的删除还是表情包里的删除，这样的话再做处理就可以了
