### ISSUE TITLE
消息列表，下拉加载之前的消息、频繁闪退问题

### ISSUE THREAD

**Issue by klforeverl** [netease-im/NIM_iOS_UIKit#43]
提示： invalid number of rows in section 0
![image](https://user-images.githubusercontent.com/7702224/26913879-65743e26-4c50-11e7-9f06-398ea5aabb26.png)

**Comment by chrisray108** [comment]
UITableView 方法被 FDIndexPathHeightCacheInvalidation 截获了，这个不是我们组件的 category ，在这里出现了崩溃。检查下自己的业务逻辑哈。
