### ISSUE TITLE
iOS 11 中会话消息布局错误。

### ISSUE THREAD

**Issue by raykle** [netease-im/NIM_iOS_UIKit#45]
<img width="318" alt="qq20170629-180558 2x" src="https://user-images.githubusercontent.com/3097366/27682757-53130bde-5cf6-11e7-9d68-c64646c299df.png">
<img width="319" alt="qq20170629-181156 2x" src="https://user-images.githubusercontent.com/3097366/27682808-765461f6-5cf6-11e7-93fb-da9c76c91415.png">

iOS 11 中刚进入聊天界面，消息 cell 的布局错误，滑动 cell 重新出现的布局就对了。

调试发现，tableView 先进入了 dataSource 方法：`cellForRowAtIndexPath`，后进入了 delegate 方法：`heightForRowAtIndexPath`,

而 cell 的布局是在 `heightForRowAtIndexPath` 中 `[self.interactor checkLayoutConfig:model];` 中的 `-calculateContent:force:` 中确定的。

不知道 iOS 11 正式发布后，方法的调用顺序会不会改回来。

**Comment by cirelir** [comment]
这个我试了，在真机上没有这个问题

**Comment by wolangerxing** [comment]
正在做iOS 11的适配，这个问题真是恶心啊。。。

**Comment by raykle** [comment]
@wolangerxing 恩，现在 11 还没发布，我们也还没解决这个问题，先等官方更新吧。。。

**Comment by xiangwangfeng** [comment]
@wolangerxing @raykle 这个问题我们会在 iOS 11 正式版发出后进行检查，如果问题仍旧存在，我们将第一时间修改

**Comment by raykle** [comment]
@xiangwangfeng 👌🏻

**Comment by yitianljt** [comment]
iOS11 sdk编译出来在iOS11手机上会有问题。

**Comment by chrisray108** [comment]
已修正
