### ISSUE TITLE
pod install 失败

### ISSUE THREAD

**Issue by sunyanyan** [netease-im/NIM_iOS_UIKit#47]
- `NIMSDK_LITE (~> 3.9.0)` required by `NIMKit/Lite (1.6.0)`

None of your spec sources contain a spec satisfying the dependency: `NIMSDK_LITE (~> 3.9.0)`.

**Comment by xiangwangfeng** [comment]
本地缓存仓库太老了，推荐使用
pod repo update --verbose 
更新一波
