### ISSUE TITLE
建议更新框架依赖库

### ISSUE THREAD

**Issue by ihomelp07** [netease-im/NIM_iOS_UIKit#48]
Specs satisfying the `SVProgressHUD (= 2.1.2), SVProgressHUD (~> 2.0.3)` dependency were found, but they required a higher minimum deployment target.

**Comment by Ryan-Wong-iOS** [comment]
建议把 SDWebImage 更新至 4.0.0；SVProgressHUD更新至 2.1.2。或者直接不指定版本吧。因为现在与其他控件冲突了。

**Comment by xiangwangfeng** [comment]
SVProgressHUD 在 NIMKit 并非必须，我们将在下一期进行移除
SDWebImage 同时将更新至最新版本 (不指定版本)
