### ISSUE TITLE
引入后，不能通过编译

### ISSUE THREAD

**Issue by xingyuemitu** [netease-im/NIM_iOS_UIKit#49]
Undefined symbols for architecture x86_64:
  "_NTESNotificationLogout", referenced from:
      ___50-[NTESSettingViewController logoutCurrentAccount:]_block_invoke_2 in NTESSettingViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
请问一下这个问题怎么解决

**Comment by xiangwangfeng** [comment]
_NTESNotificationLogout 这个符号应该是 demo 中的一个通知，而不是在 NIMKit 里，建议检查下是不是引入了多余的文件
