### ISSUE TITLE
请问自定义消息点击事件要怎么处理

### ISSUE THREAD

**Issue by xingxingc** [netease-im/NIM_iOS_UIKit#53]
比如：用户点击图片消息的话，有浏览图片大图的需求等场景，或者本地定义了一个商品消息的自定义消息，用户点击这个cell的时候，需要跳转到商品详情页，请问这中逻辑要怎么实现呢，找了好久都没找到入口，麻烦帮忙看下！

**Comment by xingxingc** [comment]
@xiangwangfeng

**Comment by xingxingc** [comment]
@xiangwangfeng

**Comment by xiangwangfeng** [comment]
可以参考阅后即焚的消息 （NTESSessionSnapchatContentView） 中的代码
一般流程是：
1.在自定义 `ContentView` 中定义点击事件
2.点击事件触发时通过 `delegate` 发起 `onCatchEvent：` 回调
3.回调传递到 `Cell`，`Cell` 发起 `onTapCell:` 回调
4.在对应的 SessionViewController 进行处理回调即可，具体参考 `NTESSessionViewController` 的 `onTapCell:` 方法

**Comment by xingxingc** [comment]
好的。谢谢你




发自网易邮箱大师
在2017年08月10日 09:49，阿毛 写道：

可以参考阅后即焚的消息 （NTESSessionSnapchatContentView） 中的代码
一般流程是：
1.在自定义 ContentView 中定义点击事件
2.点击事件触发时通过 delegate 发起 onCatchEvent： 回调
3.回调传递到 Cell，Cell 发起 onTapCell: 回调
4.在对应的 SessionViewController 进行处理回调即可，具体参考 NTESSessionViewController 的 onTapCell: 方法
