### ISSUE TITLE
SDwebimage 报错

### ISSUE THREAD

**Issue by SunGuok** [netease-im/NIM_iOS_UIKit#55]
<img width="1400" alt="9c16228d-3b9d-4568-aaa5-bee6cfb8ed15" src="https://user-images.githubusercontent.com/16420441/29359150-0f1923de-82b0-11e7-8381-5d0aa99526c7.png">

**Comment by chrisray108** [comment]
这个是手动拖的 NIMKit 代码吗？   NIMKit 的 SDWebImage 依赖已经升级到 4.0.0了

**Comment by SunGuok** [comment]
直接执行了 pod install


![9c16228d-3b9d-4568-aaa5-bee6cfb8ed15](https://user-images.githubusercontent.com/16420441/29394114-e1149a6e-833a-11e7-80c2-34af5c830a5b.png)

**Comment by xiangwangfeng** [comment]
可以给我们看下 podfile 文件么？

**Comment by SunGuok** [comment]
😅，刚才发错图了

<img width="1400" alt="9f00c19a-8b50-4727-9c1f-41daac611332" src="https://user-images.githubusercontent.com/16420441/29394308-15d85820-833c-11e7-9d01-f0a1482a4e64.png">

**Comment by xiangwangfeng** [comment]
请指明 NIMKit version，如 1.8.1。在新老版本之间我们升级了依赖的 SDWebImage 版本号
