### ISSUE TITLE
Please upgrade TZImagePickerController to 1.8.x

### ISSUE THREAD

**Issue by tinpont** [netease-im/NIM_iOS_UIKit#57]
It's better to keep third-party framework up to date.

**Comment by witchnana** [comment]
可否升级TZImagePickerController到最新版本，TZImagePickerController更新提示说里面有用到私有API可能会影响到APP上架

TZImagePickerController

A clone of UIImagePickerController, support picking multiple photos、original photo、video, also allow preview photo and video, support iOS6+.
一个支持多选、选原图和视频的图片选择器，同时有预览功能，支持iOS6+。

重要提示：1.9.0版本已发布，移除了"prefs:root="的调用，这个API已经被列为私有API，请大家尽快升级。

**Comment by chrisray108** [comment]
TZImagePickerController is update to 1.9.0

**Comment by tinpont** [comment]
Thanks, @chrisray108 .
