### ISSUE TITLE
demo pod之后，打开工程运行出错

### ISSUE THREAD

**Issue by devXiaoL** [netease-im/NIM_iOS_UIKit#58]
下载地址是：http://netease.im/im-sdk-demo

**Comment by xiangwangfeng** [comment]
贴一下具体的错误信息呗

**Comment by xiangwangfeng** [comment]
暂时先关闭这个 issue。
如果超过 7 天没有得到任何回应，我们就先暂时关闭对应 issue，如果你发现问题仍然存在，欢迎重新打开这个 issue。
