### ISSUE TITLE
NTESAudioChatViewController中peerUid判断有问题

### ISSUE THREAD

**Issue by MirrorZyb** [netease-im/NIM_iOS_UIKit#59]
` NSString *peerUid = ([[NIMSDK sharedSDK].loginManager currentAccount] == self.callInfo.caller) ? self.callInfo.callee : self.callInfo.caller;`
两个字符串用==号做判断这样真的可以吗。。。。

**Comment by xiangwangfeng** [comment]
嗯，这里是个手误，我们会在下个星期的版本进行修正
