### ISSUE TITLE
Prefix.pch报错

### ISSUE THREAD

**Issue by heyehao2008** [netease-im/NIM_iOS_UIKit#6]
下载项目后，执行pod install
下载完所有依赖库后，打开xcode。有一个错误 'NIMAVChat.h' file not found
注释该行后，又出现NIMAVChatDefs.h file not found
貌似这个NIMAVChat开头的类都没有

**Comment by chrisray108** [comment]
刚试了下没啥问题呢，pod install 有报错吗？

**Comment by heyehao2008** [comment]
<img width="679" alt="nimdemo-prefix pch xcode at 11 34 26" src="https://cloud.githubusercontent.com/assets/7590049/20860355/1827a586-b9b1-11e6-90ed-f7448d6cb14e.png">
pod 安装后如上图，是有pod没有安装上么？

**Comment by chrisray108** [comment]
SDK装成了没有音视频版本的了，检查下你的 Podfile 呢？ 建议用我们最新版本 1.0.4 的 NIMKit。
