### ISSUE TITLE
pod install NIMKit

### ISSUE THREAD

**Issue by tinvyhxx** [netease-im/NIM_iOS_UIKit#60]
[!] Error installing NIMSDK_LITE
[!] /usr/bin/git clone https://github.com/netease-im/NIM_iOS_SDK_Lite.git /var/folders/6h/z19csss90756v8dlv224n28h0000gn/T/d20170918-89171-1na5uk --template= --single-branch --depth 1 --branch 3.2.5

Cloning into '/var/folders/6h/z19csss90756v8dlv224n28h0000gn/T/d20170918-89171-1na5uk'...
remote: Repository not found.
fatal: repository 'https://github.com/netease-im/NIM_iOS_SDK_Lite.git/' not found
github page return 404 of https://github.com/netease-im/NIM_iOS_SDK_Lite.git

**Comment by xiangwangfeng** [comment]
因为历史原因，cocoapods 部分我们已经废弃了 3.5.0 之前的版本，建议升级版本。

**Comment by coooliang** [comment]
@xiangwangfeng 我已经是最新版本的cocoapods了还是不行，建议自己尝试一下。

pod --version
1.6.0.beta.1
