### ISSUE TITLE
聊天界面的时间小条能不能设置成24小时

### ISSUE THREAD

**Issue by zsj1992** [netease-im/NIM_iOS_UIKit#61]
聊天界面的时间小条能不能设置成24小时

**Comment by cirelir** [comment]
自己改一下NIMKitUtil文件

**Comment by xiangwangfeng** [comment]
目前有两种方法来实现这个需求
1.修改源码，直接修改 NIMKitUtil 对应的格式化时间的方法
2.通过 swizzle 的方法对 NIMKitUtil 格式化时间方法进行 hook ，可以在不修改源码的情况下进行调整

后期我们会考虑将这些设置也做成配置开放

**Comment by zsj1992** [comment]
感谢
