### ISSUE TITLE
什么时候支持 SDWebImage 4.1.0 

### ISSUE THREAD

**Issue by zhaoyunyi** [netease-im/NIM_iOS_UIKit#62]

**Comment by xiangwangfeng** [comment]
对我们来说更重要的是提供稳定的功能，而不是跟进依赖第三方库的版本。所以在第三方库不发生重大变更的前提下，我们基本不会主动升级第三方库。在后期我们会考虑将可有可无的第三方库进行重写或是重命名。
对于你这种需求，有两种解决方案
1.手动集成，替换 SDWebImage
2.维护 NIMKit 的私有 podspec，重写 podspec 内容
