### ISSUE TITLE
Xcode 9.0编译不通过

### ISSUE THREAD

**Issue by zsading** [netease-im/NIM_iOS_UIKit#64]
#### error:Multiple methods named 'height' found with mismatched result, parameter type or attributes
![image](https://user-images.githubusercontent.com/4957556/30637031-cccdbff4-9e29-11e7-8b52-5e8598e9e5a3.png)

####The following code can solve this problem
 ```
NIMTimestampModel *timeModel = modelInArray;
 cellHeight = [timeModel height];
```

**Comment by chrisray108** [comment]
这个问题已经修复了，更新到最新版本即可。
