### ISSUE TITLE
Xcode9上运行demo直接报错

### ISSUE THREAD

**Issue by TML007** [netease-im/NIM_iOS_UIKit#65]
1、//        __weak typeof (self) wself = self;
//        self.taskId = [[NIMAVChatSDK sharedSDK].avchatNetDetectManager startDetectTaskForVideo:YES
//                                                                                    completion:^(NIMAVChatNetDetectResult * _Nonnull result) {
//            wself.netDetectResultTextView.text = [NSString stringWithFormat:@"%@net detect result:\n%@\n------------\n", wself.netDetectResultTextView.text, result];
//            wself.taskId = 0;
//            [wself updateDetectButton];
//        }];
2、//        case NIMNetCallNetStatusPoor:
//            netState = @"网络一般:";
//            break;

**Comment by xiangwangfeng** [comment]
请贴一下错误信息

**Comment by xiangwangfeng** [comment]
1.9.1 版本因为接口差异所以有问题，已修复
