### ISSUE TITLE
NIMKit 或者demo里面有关于掉线的监听吗?

### ISSUE THREAD

**Issue by zsj1992** [netease-im/NIM_iOS_UIKit#66]

**Comment by xiangwangfeng** [comment]
参考 http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/iOS%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90?#断线重连机制
