### ISSUE TITLE
重发消息

### ISSUE THREAD

**Issue by zsj1992** [netease-im/NIM_iOS_UIKit#68]
由于在对方黑名单发送消息失败,点击红色感叹号❗️重发消息,其实仍然是没发成功,但是感叹号不见了,对方没收到消息

**Comment by xiangwangfeng** [comment]
目前的服务设计如此：一旦被拉黑，被拉黑端发送消息给操作者时，第一次会返回错误。如果选择重发，系统会返回成功，但是这条消息仍是没有投递到对端的。
