### ISSUE TITLE
pod 完整版下来，根本编译不过，一堆错误。

### ISSUE THREAD

**Issue by aazhou** [netease-im/NIM_iOS_UIKit#69]
issue#1:
NIMKitDependency.h => #import "uiview+WebCache.h"  根本没有这个文件.

issue#2:
NIMAvatarImageView.h
这个文件下一堆的错误！SDExternalCompletionBlock根本找不到，等等！

请更新pod

**Comment by chrisray108** [comment]
看起来全是 SDWebImage 库的报错？ 我们 pod 是有指定依赖 SDWebImage 的，依赖版本目前是 4.0.0，检查下你 pod 过程中依赖安装是否正确？(比如有没有出现错误或者警告的日志，检查 pod 下来的文件有没有 SDWebImage 库等等)

**Comment by aazhou** [comment]
FULL里面为什么没有视频聊天的controller？你看到你们demo里面有，但这样去集成各种麻烦，能不把集成到pod里，直接pod之后，直接就可以用？

**Comment by xiangwangfeng** [comment]
视频界面不属于我们这个 UI 组件的范围，所以没有加到 pod 里。 UI 组件主要是提供 IM 相关的会话界面功能
