### ISSUE TITLE
pod install 需要账号密码

### ISSUE THREAD

**Issue by WithdrwnKing** [netease-im/NIM_iOS_UIKit#70]
![image](https://user-images.githubusercontent.com/8319576/31331540-57a6eefc-aca8-11e7-9c56-cd0932e45043.png)

去除NIMKit后可以install成功

**Comment by xiangwangfeng** [comment]
这个不是 pod 需要账号密码，而是 3.5.0 之前的 NIMSDK_LITE 仓库和并不维护在当前仓库，所以我们选择废弃了那个仓库
