### ISSUE TITLE
clone下来之后，xcode提示依赖冲突

### ISSUE THREAD

**Issue by coneycode** [netease-im/NIM_iOS_UIKit#72]
clone下来，执行pod install --repo-update后，项目提示

Apple Mach-O Linker(Id) Error
Linker command failed with exit code 1 (use -v to see invocation)

**Comment by xiangwangfeng** [comment]
有详细的错误信息么？ 具体因为什么原因导致的 link 错误

**Comment by coneycode** [comment]
ld: framework not found FileProvider for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
这个问题已经解决了，估计你们开发时应该使用的xcode9，我用的xcode8。多谢~
