### ISSUE TITLE
麻烦问一下,NIMInputView的高度怎么自定义设置的,没找到相关属性设置

### ISSUE THREAD

**Issue by iGump** [netease-im/NIM_iOS_UIKit#73]
麻烦问一下,NIMInputView的高度怎么自定义设置的,没找到相关属性设置,老的NIMKit里面好像plist文件里面可以设置.最新的sdk怎么设置呀

**Comment by iGump** [comment]
下面输入框的高度怎么设置的呀,有人么,求解答呀!

**Comment by iGump** [comment]
<img width="379" alt="2017-10-23 09 35 18" src="https://user-images.githubusercontent.com/5423184/31868795-8a5d7de2-b7d5-11e7-8080-cca5e9753346.png">
就是中间输入的地方,他的高度不能调整么?

**Comment by chrisray108** [comment]
这个高度调整了，两边的按钮大小,间距也需要调整，切换到发语音界面后，界面排版也要做对应变化。暂时不支持定制。

**Comment by iGump** [comment]
你们之前的sdk是可以设置这个的高度...现在下面这一块直接全部写死了,不能理解...

**Comment by chrisray108** [comment]
之前的也不行，没有开过这样的接口哦

**Comment by iGump** [comment]
<img width="618" alt="2017-10-27 11 20 46" src="https://user-images.githubusercontent.com/5423184/32086617-0fd91bc6-bb09-11e7-9511-408ca7b72525.png">
最上面两个属性,不是么?之前SDK里面预留有,现在直接写死了

**Comment by chrisray108** [comment]
哦，plist之前是有放出过，但是因为会引起排版问题所以去掉了
