### ISSUE TITLE
如何开启图片传输功能？

### ISSUE THREAD

**Issue by coneycode** [netease-im/NIM_iOS_UIKit#75]
我看描述中Nim_Kit中提供发送图片，位置等功能，但是demo运行起来的时候没有这些内容。文档中也没找到如何开启。

**Comment by xiangwangfeng** [comment]
更复杂的 demo 功能可以参考 http://netease.im/im-sdk-demo 中完整的产品 demo 中对 UI 组件的使用
也可以先行阅读 https://github.com/netease-im/NIM_iOS_UIKit/blob/master/Documents/nim_custom_ui.md 的内容

**Comment by coneycode** [comment]
有介绍NIM_Kit的东西吗？你官网的链接介绍的是NIM_SDK,你给的markdown里没有提到这一点。
还是那个问题，这个NIM_IOS_KIT项目描述中写了，该项目提供发送图片，位置等功能，但是demo下载下来，并没有发现这个功能，如何配置呢？
