### ISSUE TITLE
网易云信 iOS UI 组件，提供聊天界面，文本消息，图片消息，语音消息，视频消息，地理位置消息，自定义消息（阅后即焚）等消息示例，在哪呢？

### ISSUE THREAD

**Issue by coneycode** [netease-im/NIM_iOS_UIKit#78]
之前提过这个问题，没有做出解答。

有介绍NIM_Kit的东西吗，
1. 给出官网的链接介绍的是NIM_SDK
2. 给的markdown里没有提到UI组件的图片消息在哪开启。

还是那个问题，这个NIM_IOS_KIT项目描述中写了，该项目提供发送图片，位置等功能，但是demo下载下来，只有自定义消息，并没有发现这个功能，我自己也尝试查找没找到，Android的UIKit一切正常，辛苦回答下，该如何配置呢？

**Comment by chrisray108** [comment]
自己建立一个类 实现 NIMSessionConfig 协议中的 - (NSArray *)mediaItems 方法，如果需要发图片的话，可以使用默认实现好的 MediaItem。

示例：

```objc
- (NSArray *)mediaItems{
    NSArray *defaultMediaItems = [NIMKitUIConfig sharedConfig].defaultMediaItems;
    return defaultMediaItems;
}
```
文档的话，目前只有在 《项目结构介绍》的会话配置章节有简单介绍，后续会补充完整。
组件 Demo 中已经添加了示例。

**Comment by coneycode** [comment]
懂了！多谢~我就是不清楚默认的MediaItem类叫什么名字，多谢哈~
