### ISSUE TITLE
第一次进入聊天页面,有闪屏

### ISSUE THREAD

**Issue by iGump** [netease-im/NIM_iOS_UIKit#79]
第一次进入聊天页面,有闪屏现象,拉过来的数据是文字还好一点,如果有图片很明显

**Comment by chrisray108** [comment]
没有复现。手机系统是多少？用的是我们提供的 example 工程吗？

**Comment by xiangwangfeng** [comment]
顶起关闭无响应 issue，如有问题，请重开当前 issue
