### ISSUE TITLE
提点建议

### ISSUE THREAD

**Issue by hydyy** [netease-im/NIM_iOS_UIKit#8]
具体做了一下，发现一些小问题。

1、 关于bundle资源文件的路径， 三个bundle的设置是不统一的，pod引入之后，需要设置resource的资源目录为mainBundle。 其他两个则不需要，这很奇怪，还是写清楚会比较好 ，免得开发者自己跟代码。而且最好还是统一吧。 

2、cell相关的一些自定义，比如说cell的背景色，我看到是代码里直接写死,其实完全也可以抛出的。

3、以后是否可以加个版本更新说明，我们正好赶在3.2前做的集成，然后你们就发布3.2了，并不知道具体需要修改哪里。一点一点摸出来的，蛮费时间。

希望可以采纳

**Comment by chrisray108** [comment]
第一个问题是指上层使用到了 resource.bundle 里的图片吗？如果是使用了 resource.bundle 里的图片，建议直接 使用 UIImage+NIM.h 里的扩展方法 nim_imageInKit:

二三问题我们会在以后的版本迭代中解决的，感谢您的反馈 :)

**Comment by hydyy** [comment]
NSBundle * mainBundle = [NSBundle mainBundle];
NSString * resource = [mainBundle pathForResource:@"NIMKitResource"
                                                       ofType:@"bundle"];            
[NIMKit sharedKit].resourceBundleName = resource;

resource是需要设置mainBundle的

emoticonBundleName
settingBundleName
这两个却不需要... 统一了岂不是很好？

**Comment by chrisray108** [comment]
这个是不需要上层去赋值的，直接拿来读就可以了，具体可以参考下 UIImage+NIM 里的 nim_imageInKit: 方法实现。

**Comment by hydyy** [comment]
会报错哎。 我记得是哪个地方取图片的时候， 没有从mainbound里去取。。。

**Comment by chrisray108** [comment]
具体错误和步骤贴出来看看呢？组件里的图片都是在 resource.bundle里的呀，组件获取图片方法也全是直接去那个bundle里拿的。

**Comment by hydyy** [comment]
@implementation NIMKit
- (instancetype)init
{
    if (self = [super init]) {
        _resourceBundleName  = @"NIMKitResource.bundle";
        _emoticonBundleName  = @"NIMKitEmoticon.bundle";
        _settingBundleName   = @"NIMKitSettings.bundle";
        _firer = [[NIMKitNotificationFirer alloc] init];
        _provider = [[NIMKitDataProviderImpl alloc] init];   //默认使用 NIMKit 的实现

        _layoutConfig = [[NIMCellLayoutConfig alloc] init];
    }
    return self;
}

*UIImage (NIMKit)*
+ (UIImage *)nim_imageInKit:(NSString *)imageName{
    NSString *name = [[[NIMKit sharedKit] resourceBundleName] stringByAppendingPathComponent:imageName];
    return [UIImage imageNamed:name];
}

直接拿的图片,这个时候，不会去MainBundle里去取


========

@implementation NIMKitGlobalConfig

- (instancetype)init{
    self = [super init];
    if (self) {
        NSString *name = [[[NIMKit sharedKit] settingBundleName] stringByAppendingPathComponent:@"NIMKitGlobalSetting.plist"];
        NSString *path = [[NSBundle mainBundle] pathForResource:name ofType:nil];
        NSDictionary *globalSetting = [NSDictionary dictionaryWithContentsOfFile:path];
        
这里的时候取得是mainbundle

**Comment by chrisray108** [comment]
Bundle 说白了其实也就是个文件目录。
第一个取图片是从 resourceBundleName 这个目录里取的。
第二个取配置 plist 其实是从 settingBundleName 这个目录里取的。
两处的 name 变量其实都是拼接的目录名。
mainBundle 是资源根目录的意思，是可以通过 */* 这样的方式去拿子目录里的资源的。

**Comment by hydyy** [comment]
> 而 imageNamed 默认也是走资源根目录，其实跟 [NSBundle mainBundle] 是一个意思。
你真的试过pod引入之后，是一个意思吗？你可以测试下的。
