### ISSUE TITLE
适配 iPhone X

### ISSUE THREAD

**Issue by raykle** [netease-im/NIM_iOS_UIKit#81]
请问有适配 iPhone X 的计划吗？

**Comment by raykle** [comment]
目前 iPhone X 上发现的问题有：

【聊天界面】
底部的 `toolBar` 位置；点击 `表情按钮` 出现的表情选择底部位置；点击 **＋** 出现的面板位置；
文字输入时候，部分输入框被键盘遮挡。

**Comment by xiangwangfeng** [comment]
近期会上一个做过大量调整的版本，后期也会针对 iPhone X 做详细的兼容性测试

**Comment by raykle** [comment]
@xiangwangfeng 上周在云信客户群里问了客服，当时说还没有 iPhone X 的计划，所以我们先自己做了适配。
还有就是我们有跟云信相结合的业务开发，Kit 经常变动会导致升级了之后我们也会需要修改，还没找到什么好的办法。😓 所以还是希望能够尽量稳定一些。

**Comment by xiangwangfeng** [comment]
嗯，下个版本会有一个大更新，这以后我们基本会像 SDK 一样保证 API 的稳定性。。不过如果没有特殊理由，NIMKit 版本也不需要频繁升级，够用就好

**Comment by raykle** [comment]
@xiangwangfeng 👌🏻👌🏻

**Comment by qi995971072** [comment]
草你没的，更新版本也不说说该了哪些

**Comment by HelloiWorld** [comment]
《iPhone X从适配到放弃》，希望最好能整理给出一个简单的方式

拿对比工具把NIMKit与自己项目做了下对比，一大堆不同，尝试改了下，变动真心太大，只得找了些还不错的小修改加到项目里去了，实在是无力再改下去了

**Comment by oxape** [comment]
什么时候适配iPhone X啊

**Comment by chrisray108** [comment]
2.3.0版本已修复
