### ISSUE TITLE
ios发送的自定义消息的内容，web端接收不到

### ISSUE THREAD

**Issue by KIDFUCKER** [netease-im/NIM_iOS_UIKit#82]
您好，我在ios端发送的自定义消息。web端的content字段里没有内容。web端发送的自定义消息，ios也接收不到，请问这是正常的吗？

**Comment by chrisray108** [comment]
不正常哦，我们 Demo 的自定义消息都是全端互通的，消息收不到这种 SDK 相关的问题可以联系我们官网技术支持解决。
