### ISSUE TITLE
导航栏自定义时，聊天输入bar会被键盘挡住

### ISSUE THREAD

**Issue by DevQC** [netease-im/NIM_iOS_UIKit#84]

**Comment by chrisray108** [comment]
导航是如何自定义的？有没有相关代码我可以测试下

**Comment by DevQC** [comment]
现在是创建一个控制器，继承UIViewController，然后将一个继承NIMSessionViewController的控制器SessionViewController添加进去，然后让输入框响应，输入条就会下移
if (!_sessionVC) {
        _sessionVC = [[SessionViewController alloc]initWithSession:_session];
        [self addChildViewController:_sessionVC];
        CGFloat sessionY = AdaptedSize(200);
        _sessionVC.view.frame = CGRectMake(0, sessionY, SCREEN_WIDTH, SCREEN_HEIGHT - sessionY);
        [self.view addSubview:_sessionVC.view];
    }

**Comment by chrisray108** [comment]
哪个版本的组件？

**Comment by DevQC** [comment]
最新的版本，我改好了在NIMInputView类中
在- (void)refreshStatus:(NIMInputStatus)status
{
    self.status = status;
    [self.toolBar update:status];
    switch (status) {
        case NIMInputStatusText:
        case NIMInputStatusAudio:{
            if (self.toolBar.showsKeyboard) {
/******修改点：加了个self.keyBoardHeight*******/
                self.nim_top = self.superview.nim_height - self.keyBoardHeight - self.toolBar.nim_height;
            }else{
                self.nim_top = self.superview.nim_height - self.toolBar.nim_height;
            }
            break;
        }
        case NIMInputStatusMore:
        case NIMInputStatusEmoticon:
            self.nim_bottom = self.superview.nim_height;
            break;
        default:
            break;
    }
}

**Comment by chrisray108** [comment]
下一版本弹出逻辑做了重构，可以试试，如果还有问题再打开issue。

**Comment by DevQC** [comment]
好的，谢谢
