### ISSUE TITLE
请问是用的什么架构

### ISSUE THREAD

**Issue by d-jiang** [netease-im/NIM_iOS_UIKit#85]
你好，请问NIMKit用的是什么架构，我在看的时候对Adapter Interactor configuator 这些名词理解很是费劲。可否提供这方面的信息，谢谢

**Comment by xiangwangfeng** [comment]
比较接近 VIPER 或者说 clean-swift，具体可以参考 https://github.com/netease-im/NIM_iOS_UIKit/blob/master/Documents/nim_arch.md 和  https://clean-swift.com/

**Comment by d-jiang** [comment]
谢谢回复，NIM 的 Demo 是到目前为止，我看过的 Demo 中质量最高的，多谢你们的分享
