### ISSUE TITLE
Cocoapods里面的NIMKit库能否也及时的更新？

### ISSUE THREAD

**Issue by byk04712** [netease-im/NIM_iOS_UIKit#86]
项目里用到了NIMKit库，参考官网的Demo，但是我的NIMSDK和NIMKit 是通过 cocoapods 来安装的，发现demo中有代码引用了新的头文件，但是NIMSDK里没有。

**Comment by xiangwangfeng** [comment]
NIMKit 和 NIMSDK 大部分情况下是同步更新的。但是有少数情况下，我们会只更新 NIMKit （小改动）而不更新 DEMO 中的 NIMKit。
用 CocoaPods 的版本必然还是最新的。如果发现 NIMKit 版本不是最新，请执行 pod repo update 更新本地 CocoaPods 仓库
