### ISSUE TITLE
NIM_iOS_Demo 有仓库吗？

### ISSUE THREAD

**Issue by raykle** [netease-im/NIM_iOS_UIKit#88]
http://netease.im/im-sdk-demo
请问这个网址上的 Demo 有仓库吗？

![image](https://user-images.githubusercontent.com/3097366/32884408-2ee2b0e4-caf5-11e7-8def-8ba31d6ac886.png)

**Comment by xiangwangfeng** [comment]
这部分没有仓库，可以直接在官网下载。缺点是没办法看到更新日志 😔

**Comment by raykle** [comment]
😔
