### ISSUE TITLE
我想使用tableView的其他代理方法

### ISSUE THREAD

**Issue by MirrorZyb** [netease-im/NIM_iOS_UIKit#89]
在不修改NIMKit的方式，如何配置

**Comment by chrisray108** [comment]
目前只暴露出一个`- (void)tableView:(UITableView *)tableView willDisplayCell:(UITableViewCell *)cell forRowAtIndexPath:(NSIndexPath *)indexPath;` 代理，在协议 `NIMMessageCellDelegate` 中，直接在你继承的 SessionViewController 中继承即可。
其他事件回调基本可以在其他配置中解决，详情参考 [界面配置文档](https://github.com/netease-im/NIM_iOS_UIKit/blob/master/Documents/nim_custom_ui.md)

如果还有 tableview 的代理需求不能满足，欢迎再提 issue 讨论
