### ISSUE TITLE
V2.1.0 无法下拉获取历史记录

### ISSUE THREAD

**Issue by DevQC** [netease-im/NIM_iOS_UIKit#90]
Demo里面的代码下面代码返回 nil
- (UIRefreshControl *)findRefreshControl
{
    for (UIRefreshControl *subView in self.tableView.subviews) {
        if ([subView isKindOfClass:[UIRefreshControl class]]) {
            return subView;
        }
    }
    return nil;
}

**Comment by chrisray108** [comment]
2.1.1 版本已修复
