### ISSUE TITLE
聊天室获取用户信息，必须传入message对象，如果是点击头像哪里取得到message？

### ISSUE THREAD

**Issue by DevQC** [netease-im/NIM_iOS_UIKit#91]
NSAssert(option.message, @"message must has value in chatroom");

- (BOOL)onTapAvatar:(NSString *)userId{//这里哪里取得到message？} 

NIMKit V2.1.0

**Comment by chrisray108** [comment]
这个问题我们会在 v2.3.0 版本中优化，将回调 message 上来，可以留意下个月的版本更新 :)

**Comment by chrisray108** [comment]
fix on 2.3.0
