### ISSUE TITLE
cocoapods集成的NIMKit，如何避免update的时候覆盖NIMKitSettings.bundle等文件

### ISSUE THREAD

**Issue by MirrorZyb** [netease-im/NIM_iOS_UIKit#92]

**Comment by chrisray108** [comment]
2.2.0 版本以后 NIMKitSettings 已经修改成了配置 NIMKitConfig 对象属性，可以前往[更新日志](https://github.com/netease-im/NIM_iOS_UIKit/blob/master/Documents/nim_changelog.md)查看详情

**Comment by jonsnowwinterfell** [comment]
我在resource  里怎么没有发现NIMKitSettings.bundle     只有NIMKitResource.bunndle 和 NIMKitEmoticon.bundle
