### ISSUE TITLE
为什么下载你的demo后运行不了

### ISSUE THREAD

**Issue by FrankChung1121** [netease-im/NIM_iOS_UIKit#93]
不管是直接下载运行那个demo还是通过cocoapods集成到工程中,你的代码都会报一堆的错,重新pod install后还是有错,总运行不起来,为什么会这样?

**Comment by xiangwangfeng** [comment]
具体什么错误可以贴出来看下

**Comment by FrankChung1121** [comment]
在NIMSessionTableAdapter类中的返回tableView高度的代码报错:
cellHeight = [modelInArray height];

**Comment by FrankChung1121** [comment]
下载你的demo后,打开你的example工程,直接pod install后,发现报错,再查看你的podfile,发现里面的pod是这样写的:pod 'NIMKit', :path => '../'
你这是还要指定路径吗?我把后面的路径去掉后,pod install是成功了,但是还有两个地方报错,一个是cellHeight = [modelInArray height];这行报错
还有一行报错的代码是:NSArray *defaultMediaItems = [NIMKit sharedKit].config.defaultMediaItems;
报找不到NIMKit

**Comment by chrisray108** [comment]
1. cellHeight = [modelInArray height]; 这个代码是很早之前的了，确认下你组件库的版本，最新的是 2.2.0
2.pod 'NIMKit', :path => '../' 指的是安装本地的开发环境下的 pods 仓库，你可以在 cocoapods 的[这里](https://guides.cocoapods.org/making/making-a-cocoapod.html)查看相关教程
3.NIMKit 如果都找不到说明你 pod install 并没有成功，建议仔细看下 pod install 打印出的日志，排查下错误，必要时可以加上 --verbose 选项

**Comment by FrankChung1121** [comment]
我是直接点击download下载的代码,解压后cd到example里面,然后直接pod install会报错,删除podfile文件里面的路径,保留pod 'NIMKit',这样没有指定版本号应该默认就是下载最新的库啊,再次pod install就成功了,然后我运行工程发现cellHeight = [modelInArray height]代码还是有的,而且报错,说明一下,我的cocoapods是没问题的,我自己的工程现在也在用,不明白为什么就是你的不行,难道只有我一个人遇到这个问题?

**Comment by chrisray108** [comment]
首先你需要 pod repo update 一下才能下到最新的版本的库，一开始 pod install 报错也是有问题的，建议你把日志贴出来看一看

**Comment by jonsnowwinterfell** [comment]
: /Users/edz/Desktop/NIM_iOS_UIKit-master/Example/Pods/Target Support Files/Pods-DemoApplication/Pods-DemoApplication.debug.xcconfig: unable to open file (in target "DemoApplication" in project "DemoApplication") (in target 'DemoApplication')  这是什么鬼

**Comment by jonsnowwinterfell** [comment]
你们上传的demo  自己 都不跑一下么        0     0

**Comment by sevenuncler** [comment]
这个Example里的demo暂时没维护了
