### ISSUE TITLE
如何在一个消息体里添加多个图片

### ISSUE THREAD

**Issue by shaveKevin** [netease-im/NIM_iOS_UIKit#94]
RT

**Comment by xiangwangfeng** [comment]
可以通过自定义消息（CustomeMessage）+自定义消息内容（CustomContentView） 来实现，具体详见 https://github.com/netease-im/NIM_iOS_UIKit/blob/master/Documents/nim_custom_message.md

**Comment by shaveKevin** [comment]
多个图片当做一条自定义消息发送的时候，上传图片的时候需要我们主动调用云信的 upload文件的接口吗？还是说我们发送一个data到消息体里面？有没有具体的实现思路。

**Comment by xiangwangfeng** [comment]
由于是多个文件，所以需要直接调用云信上传接口上传，上传后拿到 url 将具体的信息打包的 json 里面然后封装到 NIMCustomObject 里面即可。具体可以参考 DEMO 中几种自定义消息的实现逻辑。

**Comment by shaveKevin** [comment]
好的 谢谢
