### ISSUE TITLE
输入框不能在不改源码的情况下深度定制

### ISSUE THREAD

**Issue by ghostlordstar** [netease-im/NIM_iOS_UIKit#95]
比如说：
1.在工具栏上直接添加一个调起相册的按钮
2.自定义语音录制的指示图，添加声波展示等功能

这些都需要修改源码，维护起来很麻烦，不知道这个需求有没有排期？

**Comment by xiangwangfeng** [comment]
@chrisray108

**Comment by chrisray108** [comment]
有这个计划，预计在1月底的版本放出，需要继承 NIMToolBar 。

**Comment by shenguanjiejie** [comment]
@chrisray108 1月底这个版本 可以支持把整个InputView替换掉么 因为我们的需求不仅要定制 还要自己来控制InputView的展开和收缩高度

**Comment by chrisray108** [comment]
在 sessionConfig 里将 disableInputView 置成YES，然后再加上自己的输入框即可，不过这样的话当键盘上升和下降的时候，会话页气泡的变动也需要自己来控制了
