### ISSUE TITLE
气泡背景图拉伸区域不能自定义

### ISSUE THREAD

**Issue by ghostlordstar** [netease-im/NIM_iOS_UIKit#96]
希望把气泡背景图拉伸区域接口暴露在外面

**Comment by ghostlordstar** [comment]
看错了，找到接口了

**Comment by eric1202** [comment]
用了自定义的图片拉伸有问题 系统的气泡却不会

[NIMKit sharedKit].config.rightBubbleSettings.textSetting.normalBackgroundImage = [[UIImage imageNamed:@"im_bg"]imageByTintColor:[UIColor colorWithHexString:@"#A2A6B9"]];
![截屏2019-12-30上午10 26 28](https://user-images.githubusercontent.com/11612443/71566006-e9b8b200-2aee-11ea-8336-e30e846ae4b0.png)

**Comment by eric1202** [comment]
sdk版本是  2.12.10
