### ISSUE TITLE
如何在一个自定义消息体里面附带多张图片

### ISSUE THREAD

**Issue by QQQQEEEE** [netease-im/NIM_iOS_UIKit#98]
如何在一个自定义消息体里面附带多张图片，有没有demo给参考一下。万分感谢。

**Comment by xiangwangfeng** [comment]
参考这个 issue https://github.com/netease-im/NIM_iOS_UIKit/issues/94

**Comment by weinierfei** [comment]
如果我一次性选择9张图片上传,我调用upload接口后,需要等到这9张图都上传完毕后将图片地址打包然后在发送消息吧  这个过程怎么控制  能不能再demo里给一个示例

**Comment by weinierfei** [comment]
@xiangwangfeng

**Comment by xiangwangfeng** [comment]
这种同时上传 N 份等待的实现可以通过信号量或者队列实现
这个由于不属于组件的范畴内，只能给出大致思路，具体实现还是要上层自行实现

**Comment by fengong** [comment]
> 这种同时上传 N 份等待的实现可以通过信号量或者队列实现
> 这个由于不属于组件的范畴内，只能给出大致思路，具体实现还是要上层自行实现

同时上传 N 份，怎么控制消息发送过程和 UI 百分比显示同步？没有找到合适的点进行修改
