### ISSUE TITLE
你好 用lite版本sdk  贴纸在聊天cell中显示不出来了？咋解决 急

### ISSUE THREAD

**Issue by hhb19900618** [netease-im/NIM_iOS_UIKit#99]

**Comment by chrisray108** [comment]
贴纸指的是什么？

**Comment by hhb19900618** [comment]
自定义表情啊 大的表情

**Comment by chrisray108** [comment]
大的贴图表情属于自定义消息，需要自己在上层构建自定义消息去做的
点击贴图的回调在 NIMInputProtocol.h 里，直接在 SessionViewController 里重写即可

```objc
- (void)onSelectChartlet:(NSString *)chartletId
                 catalog:(NSString *)catalogId;
```

如何构造自定义消息请参考[这里](https://github.com/netease-im/NIM_iOS_UIKit/blob/master/Documents/nim_custom_message.md)
